services:
  frontend:
    build:
      context: ./frontend
      target: prod
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.docker.network=public

      # Route by domain
      - traefik.http.routers.delegence.rule=Host(`waqt.fyi`) || Host(`www.waqt.fyi`)
      - traefik.http.routers.delegence.entrypoints=websecure
      - traefik.http.routers.delegence.tls=true
      - traefik.http.routers.delegence.tls.certresolver=letsencrypt

      # Container port nginx listens on
      - traefik.http.services.delegence.loadbalancer.server.port=80

networks:
  public:
    external: true
